In [2]:
import numpy as np
class MinHeap:
  def __init__(self, capacity):
    self.__size=0
    self.__arr=np.zeros(capacity+1,dtype=int)

  def insert(self, key):
    self.__size+=1
    self.__arr[self.__size]=key
    self.swim(self.__arr,self.__size)

  def swim(self,arr,size):
    if size<=1:
      return
    else:
      parent=arr[size//2]
      if parent>arr[size]:
        arr[size],arr[size//2]=arr[size//2],arr[size]
        self.swim(arr,size//2)

  def extractMin(self):
    root=self.__arr[1]
    self.__arr[1]=self.__arr[self.__size]
    self.__size-=1
    self.sink(self.__arr,1)
    return root

  def sink(self,arr,ind):
    if self.__size==0:
      return
    else:
      left=2*ind
      right=(2*ind)+1
      if left<=self.__size and right<=self.__size:
        if arr[left]<arr[right]:
          min=left
        else:
          min = right
        if min<ind:
          arr[ind],arr[min]=arr[min],arr[ind]
        self.sink(arr,min)
      elif left <= self.__size and right > self.__size:
        arr[ind], arr[left] = arr[left], arr[ind]

  def sort(self, arr):
    temp=MinHeap(len(arr))
    for i in range(len(arr)):
      temp.insert(arr[i])
    print(temp.get_arr()[1::])

  def sort2(self, arr):
    temp=MinHeap(len(arr))
    sorted_arr=np.zeros(len(arr)+1,dtype=int)
    for i in range(len(arr)):
      temp.insert(arr[i])
    for i in range(len(arr)):
      sorted_arr[i]=temp.extractMin()      
    sorted_arr[0],sorted_arr[len(sorted_arr)-1]=sorted_arr[len(sorted_arr)-1],sorted_arr[0]
    print(sorted_arr[1::])
    
  def get_arr(self):
    return self.__arr
  def print_heap(self):
    print(self.__arr)

In [3]:
#DRIVER CODE
heap = MinHeap(10)
heap.insert(15)
heap.insert(10)
heap.insert(20)
heap.insert(5)
heap.insert(7)
heap.insert(1)
heap.print_heap()
heap.sort([9,10,43,22,2,5])
heap.sort2([9,10,43,22,2,5])

[ 0  1  7  5 15 10 20  0  0  0  0]
[ 2  9  5 22 10 43]


In [16]:
import numpy as np

class MaxHeap:
  def __init__(self, capacity):
    self.__capacity = capacity
    self.__heap = np.zeros(self.__capacity + 1, dtype=int)
    self.__size = 0

  def insert(self, val):
    self.__size += 1
    self.__heap[self.__size] = val
    self.swim(self.__heap, self.__size)

  def swim(self, heap, index):
    if index <= 1:
      return

    else:
      parent = heap[index // 2]
      if parent < heap[index]:
        heap[index], parent = parent, heap[index]
        self.swim(heap, index // 2)

  def extractMax(self, heap):
    if self.__size == 0:
      return

    max_val = heap[1]
    heap[self.__size], heap[1] = heap[1], heap[self.__size]
    self.__size -= 1
    self.sink(heap, 1)

  def sink(self, heap, index):
    if self.__size == 0:
      return

    else:
      left = 2 * index
      right = 2 * index + 1

      if left <= self.__size and right <= self.__size:
        if heap[left] > heap[right]:
          max_child = left
        else:
          max_child = right

        heap[index], heap[max_child] = heap[max_child], heap[index]
        self.extractMin(heap, max_child)

      elif left <= self.__size and right > self.__size:
        heap[index], heap[left] = heap[left], heap[index]

  def sort(self, heap, size):
    for i in range(1, size):
      self.extractMin(heap)
      
  def print_heap(self):
    print(self.__heap)

In [19]:
#DRIVER CODE
heap = MaxHeap(10)
heap.insert(15)
heap.insert(10)
heap.insert(20)
heap.insert(5)
heap.insert(7)
heap.insert(1)
heap.print_heap()
heap.sort()

[ 0 15 10 15  5  7  1  0  0  0  0]


TypeError: MaxHeap.sort() missing 1 required positional argument: 'size'