In [70]:
import numpy as np
class MinHeap:
  def __init__(self, capacity):
    self.__size=0
    self.__arr=np.zeros(capacity+1,dtype=int)

  def insert(self, key):
    self.__size+=1
    self.__arr[self.__size]=key
    self.swim(self.__arr,self.__size)

  def swim(self,arr,size):
    if size<=1:
      return
    else:
      parent=arr[size//2]
      if parent>arr[size]:
        arr[size],arr[size//2]=arr[size//2],arr[size]
        self.swim(arr,size//2)

  def extractMin(self):
    root=self.__arr[1]
    self.__arr[1]=self.__arr[self.__size]
    self.__size-=1
    self.sink(self.__arr,1)
    return root

  def sink(self,arr,ind):
    if self.__size==0:
      return
    else:
      left=2*ind
      right=(2*ind)+1
      if left<=self.__size and right<=self.__size:
        if arr[left]<arr[right]:
          min=left
        else:
          min = right
        if arr[min]<arr[ind]:
          arr[ind],arr[min]=arr[min],arr[ind]
        self.sink(arr,min)
      elif left <= self.__size and right > self.__size:
        arr[ind], arr[left] = arr[left], arr[ind]

  def sort(self, arr):
    temp=MinHeap(len(arr))
    for i in range(len(arr)):
      temp.insert(arr[i])
    print(temp.get_arr()[1::])
    
  def get_arr(self):
    return self.__arr
  def print_heap(self):
    print(self.__arr)

In [72]:
#DRIVER CODE
heap = MinHeap(10)
heap.insert(15)
heap.insert(10)
heap.insert(20)
heap.insert(5)
heap.insert(7)
heap.insert(1)
heap.print_heap()
heap.sort([9,10,43,22,2,5])

[ 0  1  7  5 15 10 20  0  0  0  0]
[ 2  9  5 22 10 43]


In [68]:
import numpy as np
class MaxHeap:
  def __init__(self, capacity):
    self.__size=0
    self.__arr=np.zeros(capacity+1,dtype=int)

  def insert(self, key):
    self.__size+=1
    self.__arr[self.__size]=key
    self.swim(self.__arr,self.__size)

  def swim(self,arr,size):
    if size<=1:
      return
    else:
      parent=arr[size//2]
      if parent<arr[size]:
        arr[size],arr[size//2]=arr[size//2],arr[size]
        self.swim(arr,size//2)

  def extractMax(self):
    root=self.__arr[1]
    self.__arr[1],self.__arr[self.__size]=self.__arr[self.__size],0
    self.__size-=1
    self.sink(self.__arr,1)
    return root

  def sink(self,arr,ind):
    if self.__size==0:
      return
    else:
      left=2*ind
      right=(2*ind)+1
      if left<=self.__size and right<=self.__size:
        if arr[left]>arr[right]:
          max=left
        else:
          max = right
        if arr[max]>arr[ind]:
          arr[ind],arr[max]=arr[max],arr[ind]
        self.sink(arr,max)
      elif left <= self.__size and right > self.__size:
        arr[ind], arr[left] = arr[left], arr[ind]

  def sort(self, arr):
    temp=MaxHeap(len(arr))
    for i in range(len(arr)):
      temp.insert(arr[i])
    print(temp.get_arr()[1::])

  def get_arr(self):
    return self.__arr
  def print_heap(self):
    print(self.__arr)

In [71]:
#DRIVER CODE
heap = MaxHeap(10)
heap.insert(15)
heap.insert(10)
heap.insert(20)
heap.insert(5)
heap.insert(7)
heap.insert(1)
heap.print_heap()
heap.sort([9,10,43,22,2,5])

[ 0 20 10 15  5  7  1  0  0  0  0]
[43 22 10  9  2  5]


In [76]:
def workload(arr,m):
    temp=MinHeap(m)
    for i in range(m):
        temp.insert(arr[i])
    for i in range(m,len(arr),1):
        x=temp.extractMin()
        x+=arr[i]
        temp.insert(x)
    print(temp.get_arr()[1::])

#Driver code
tasks=[2,4,7,1,6]
m=4
workload(tasks,m)

[2 4 7 7]


In [77]:
def find_top_k(nums, k):
    heap = MaxHeap(len(nums))
    for i in nums:
        heap.insert(i)
    print(heap.get_arr())
    result = np.zeros(k, dtype=int)
    for i in range(k):
        result[i] = heap.extractMax()
    print(result)

#Driver code
nums = [4, 10, 2, 8, 6, 7]
k = 3 
find_top_k(nums, k)

[ 0 10  8  7  4  6  2]
[10  8  7]
